version: "3.9"
services:
  server:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/:/etc/nginx/conf.d
  api:
    build: 
      context: ../database-api/.
      dockerfile: Dockerfile-dev
    environment:
      NODE_OPTIONS: ""
    volumes:
      - ../database-api/:/app

  frontend:
    build: 
      context: ../frontend/.
      dockerfile: Dockerfile-dev
    environment:
      NODE_OPTIONS: "--openssl-legacy-provider"
    volumes:
      - ../frontend/:/app

  management:
    build: 
      context: ../management/.
      dockerfile: Dockerfile-dev
    environment:
      NODE_OPTIONS: "--openssl-legacy-provider"
      PORT: 80
    volumes:
      - ../management:/app

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: warcraft3
      MARIADB_DATABASE: vendure
      MARIADB_USER: vendor
      MARIADB_PASSWORD: warcraft3